### ISSUE TITLE
r4520 breaking changes

### ISSUE THREAD

**Issue by ArticExploit** [Sterbweise/T6Server#5]
The newest plutonium update introduced many breaking changes, rendering this project not usable. 
I and the players of my two servers rely on this for hosting, so I was wondering if this is something you plan on maintaining. 
For the time I've used it it's been extremely useful and handy to host my servers so seeing it get outdated would really suck.
Thanks in advance ✌️

**Comment by hanaemercier** [comment]
hi, do you have a fix for that?

**Comment by Sterbweise** [comment]
Not yet, i'll work on it today

**Comment by Sterbweise** [comment]
@hanaemercier  @ArticExploit 
At the moment can only join the server by console connect (connect ip:port).

Ignore Socket NIX error messages, or console errors, the server still works.

This update acts as a patch until the problem is completely solved.

![image](https://github.com/user-attachments/assets/4fad0b52-01a1-4b2a-b3fe-da2f748e4b8f)


![image](https://github.com/user-attachments/assets/4760140e-7ec5-4753-a4c8-c3e57919d297)

**Comment by ArticExploit** [comment]
nice, means we're already at a good point, thanks for your work man. If you have a "buy me a coffee" or whatever else donation link I'd be happy to pitch in with a little something.

**Comment by Sterbweise** [comment]
Hi, the latest release is here. It fixes the r4520 update, many problems, and improves stability and architecture.

#### ⚠️ Attention - Significant Modifications

I advise you to read [the release notes](https://github.com/Sterbweise/T6Server/releases) to be more aware.

The most important change is the new installation process and the architecture to run your server well.

For the installation, take a look here: [#installation](https://github.com/Sterbweise/T6Server/blob/main/README.md#installation)

---

**Full documentation available: [#documentation](https://github.com/Sterbweise/T6Server/blob/main/README.md)**
